version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: charmops
      POSTGRES_PASSWORD: charmops
      POSTGRES_DB: charmops
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
